<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.3</Version>
    <Authors>Rojo</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/rojo1585/Red.FTP</RepositoryUrl>
    
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <PackageReleaseNotes>
      -Fix FTP Connection Bug
    </PackageReleaseNotes>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="icon.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include=".\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
