<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.0</Version>
    <Authors>Rojo</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <PackageReleaseNotes>
- Get file list from FTP server
    </PackageReleaseNotes>
  </PropertyGroup>

  

</Project>
